### PR TITLE
Enhancement: Enable no_whitespace_in_blank_line fixer

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] enables the `no_whitespace_in_blank_line` fixer
* [x] runs `php-cs-fixer fix`

Slightly related to #67.
Follows #52.

### CODE REVIEW

**Comment by glaubinix** [comment]
This conflicts now with the changes from the other PR. Can you please rebase?

**Comment by localheinz** [comment]
@glaubinix 

Rebased!

**Comment by glaubinix** [comment]
Thank you!

**Comment by localheinz** [comment]
Thank you, @glaubinix!

**Pull request merged**
