### PR TITLE
Enhancement: Enable and configure visibility_required fixer

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] enables and configures the `visibility_required` fixer
* [x] runs `php-cs-fixer fix`

Follows #52.
Spotted in #68.

### CODE REVIEW

**Comment by glaubinix** [comment]
Looks good! Ready to merge if you could also rebase this one.

**Comment by localheinz** [comment]
@glaubinix 

Rebased!

**Comment by glaubinix** [comment]
Thank you!

**Comment by localheinz** [comment]
Thank you, @glaubinix!

**Pull request merged**
